name: "ahmed khalid"

favoritesongs:
  - 'songe #1'
  - 'songe #2'
  - 'songe #3'

favoritesongs: ['songe #1', 'songe #1']

characteristic:
  age:20
  height:175
  skincolor:''

/////////////////////////////////////////////////////
on:
  push:
   /*what is the branch*/
    branches:
      - master









